#!/bin/bash

case "${1}" in

0)
	./resources/filler_vm -f ./resources/maps/map00 -p1 ./igaplich.filler -p2 resources/players/carli.filler
;;

1)
	./resources/filler_vm -f ./resources/maps/map01 -p1 ./igaplich.filler -p2 resources/players/carli.filler
;;

2)
	./resources/filler_vm -f ./resources/maps/map02 -p1 ./igaplich.filler -p2 resources/players/carli.filler
;;

3)
	./removing.out
;;

*)
	echo -n "unknown"
;;

esac